version: '3.4'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - monitoring
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

  kafka_exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka_exporter
    command: --kafka.server=kafka:9092
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus-data
    ports:
      - 9090:9090
    networks:
      - monitoring
    secrets:
      - prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    ports:
      - 3000:3000
    networks:
      - monitoring

secrets:
  prometheus.yml:
    file: config/prometheus.yml

volumes:
  grafana-data:
  prometheus-data:

networks:
  monitoring:
    external: true