server.port: 6080

management.endpoints.web.exposure.include: "*"

spring:
  kafka:
    bootstrap-servers:
    - broker:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer